- name: login
- name: signup
- name: web.leagues
  path: /leagues
- name: web.prizes
  path: /prizes
- name: web.game-rules
  path: /game-rules
- name: web.points-scoring
  path: /points-scoring
- name: web.faq
  path: /faq
- name: web.what-is-new
  path: /what-is-new
- name: web.privacy-policy
  path: /privacy-policy
- name: web.terms-and-conditions
  path: /terms-and-conditions
- name: web.fantasy
  path: /fantasy
- name: web.daily-fantasy
  path: /daily-fantasy
- name: web.dynamic-pricing
  path: /dynamic-pricing
- name: web.team-marketing
  path: /team-marketing
- name: web.subs-bank
  path: /subs-bank
