- id: pick-your-team
- id: joining-leagues
- id: manage-your-team
- id: subs-bank
- id: turbo-driver
- id: mega-driver
- id: wildcard
- id: dynamic-pricing
- id: team-lock
- id: point-scoring
- id: live-gameweek
- id: post-race
- id: postponed-cancelled
- id: others
