- id: qualifying
  events:
    - id: 1
      points: 1
    - id: 2
      points: 2
    - id: 3
      points: 3
    - id: 4
      points: 2
    - id: 5
      points: -5
    - id: 6
      points: -10
- id: qualifying-position-bonuses
  events:
    - id: 1
      points: 10
    - id: 2
      points: 9
    - id: 3
      points: 8
    - id: 4
      points: 7
    - id: 5
      points: 6
    - id: 6
      points: 5
    - id: 7
      points: 4
    - id: 8
      points: 3
    - id: 9
      points: 2
    - id: 10
      points: 1
- id: race
  events:
    - id: 1
      points: 1
    - id: 2
      points: 2
    - id: 3
      points: 3
    - id: 4
      points: 5
    - id: 5
      points: -2
    - id: 6
      points: -10
    - id: 7
      points: -20
  hasNote: true
- id: finishing-position-bonuses
  events:
    - id: 1
      points: 25
    - id: 2
      points: 18
    - id: 3
      points: 15
    - id: 4
      points: 12
    - id: 5
      points: 10
    - id: 6
      points: 8
    - id: 7
      points: 6
    - id: 8
      points: 4
    - id: 9
      points: 2
    - id: 10
      points: 1
- id: streaks
  events:
    - id: 1
      points: 5
    - id: 2
      points: 10
    - id: 3
      points: 5
    - id: 4
      points: 10
  hasNote: true
- id: sprint-qualifying-points-structure
  events:
    - id: 1
      points: 1
    - id: 2
      points: 1
    - id: 3
      points: 2
    - id: 4
      points: 3
    - id: 5
      points: -1
    - id: 6
      points: -5
    - id: 7
      points: -10
  hasNote: true
- id: sprint-qualifying-position-bonuses
  events:
    - id: 1
      points: 10
    - id: 2
      points: 9
    - id: 3
      points: 8
    - id: 4
      points: 7
    - id: 5
      points: 6
    - id: 6
      points: 5
    - id: 7
      points: 4
    - id: 8
      points: 3
    - id: 9
      points: 2
    - id: 10
      points: 1
  hasNote: true