- type: route
  route: web.fantasy
  labelKey: menu.main.fantasy

- type: route
  route: web.leagues
  labelKey: menu.main.leagues

- type: route
  route: web.subs-bank
  labelKey: menu.main.subs-bank

- type: route
  route: web.dynamic-pricing
  labelKey: menu.main.dynamic-pricing

- type: route
  route: web.prizes
  labelKey: menu.main.prizes

- type: route
  route: web.daily-fantasy
  labelKey: menu.main.daily-fantasy

- type: parent
  labelKey: menu.main.more
  children:
    - type: route
      route: web.game-rules
      labelKey: menu.main.game-rules
    - type: route
      route: web.points-scoring
      labelKey: menu.main.points-scoring
    - type: route
      route: web.faq
      labelKey: menu.main.faq
    - type: route
      route: web.what-is-new
      labelKey: menu.main.what-is-new
    - type: link
      url: https://www.formula1.com/
      target: formula-1
      labelText: Formula1.com
